### ISSUE TITLE
[Question] errors if no import in test file

### ISSUE THREAD

**Issue by togakangaroo** [alexweber/es6-jspm-gulp-boilerplate#7]
Hey, so this is more of a question. After getting your setup working I realized it was almost identiccal to my previous (not working) setup. After picking through it I found what seems absolutely bizarre - if the test file does not have an import at the top it seems to not be interpreted as es6 and error out at the first arrow function.

You can confirm this by removing the import from your test file - it never even gets as far as throwing a `ReferenceError`, it can't even parse the file!

I've only recently started with jspm and today is my first day playing with karma so I'll ask you - have you seen this? Do you know if this is a known issue? Any idea _whos_ issue this might be?

**Comment by alexweber** [comment]
@togakangaroo Hmmm, not entirely sure, I'll have some time to tinker with this tonight, I'll let you know!

**Comment by alexweber** [comment]
@togakangaroo So i've dug into this a bit and I'm as confused as you are... I don't seem to be getting any errors but the test definitely doesn't run without that import at the top.  I've actually replace it with `expect('Do Something').to.equal('Do Something');` so it will always pass but comment the import and it stops working.

No clue as to why since Karma is setup to use the jspm adapter...

**Comment by togakangaroo** [comment]
I've confirmed that this happens with raw jspm (and maybe even systemjs? didn't dig that deep).

[Created this issue](https://github.com/jspm/jspm-cli/issues/859)

**Comment by alexweber** [comment]
@togakangaroo Nice find!  That [comment](https://github.com/systemjs/systemjs/blob/master/lib/esm.js#L5-L6) says it all:

> good enough ES6 module detection regex

Is it really? :)
